// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZF_AuditoriaCalidad.Server.Data;

namespace ZF_AuditoriaCalidad.Server.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210630121707_Observaciones_y_cambios_minimos_en_Area_y_DetalleAuditoria")]
    partial class Observaciones_y_cambios_minimos_en_Area_y_DetalleAuditoria
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(50000);

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SubjectId")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes");
                });

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(50000);

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubjectId")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Key");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.ToTable("PersistedGrants");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ZF_AuditoriaCalidad.Server.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("ZF_AuditoriaCalidad.Shared.Area", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(240)")
                        .HasMaxLength(240);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("tblAreas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Descripcion = "Area de Produccion Nro 1",
                            Email = ""
                        },
                        new
                        {
                            ID = 2,
                            Descripcion = "Area de Produccion Nro 2",
                            Email = ""
                        },
                        new
                        {
                            ID = 3,
                            Descripcion = "Area de Produccion Nro 3",
                            Email = ""
                        },
                        new
                        {
                            ID = 4,
                            Descripcion = "Area de Produccion Nro 4",
                            Email = ""
                        },
                        new
                        {
                            ID = 5,
                            Descripcion = "Area de Produccion Nro 5",
                            Email = ""
                        });
                });

            modelBuilder.Entity("ZF_AuditoriaCalidad.Shared.Auditoria", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<bool>("DeBaja")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hora")
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<int>("MaquinaID")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("NroOrden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NroPieza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperarioID")
                        .HasColumnType("int");

                    b.Property<int>("SupervisorID")
                        .HasColumnType("int");

                    b.Property<string>("UserBajaID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MaquinaID");

                    b.HasIndex("OperarioID");

                    b.HasIndex("SupervisorID");

                    b.ToTable("tblAuditorias");
                });

            modelBuilder.Entity("ZF_AuditoriaCalidad.Shared.DetalleAuditoria", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuditoriaID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCorreccion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PuntoAuditoriaID")
                        .HasColumnType("int");

                    b.Property<int>("RespuestaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AuditoriaID");

                    b.HasIndex("PuntoAuditoriaID");

                    b.HasIndex("RespuestaID");

                    b.ToTable("tblDetallesAuditoria");
                });

            modelBuilder.Entity("ZF_AuditoriaCalidad.Shared.Maquina", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AreaID")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(240)")
                        .HasMaxLength(240);

                    b.HasKey("ID");

                    b.HasIndex("AreaID");

                    b.ToTable("tblMaquinas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AreaID = 1,
                            Descripcion = "Maquina Nro 1 del Area de Produccion Nro 1"
                        },
                        new
                        {
                            ID = 2,
                            AreaID = 1,
                            Descripcion = "Maquina Nro 2 del Area de Produccion Nro 1"
                        },
                        new
                        {
                            ID = 3,
                            AreaID = 1,
                            Descripcion = "Maquina Nro 3 del Area de Produccion Nro 1"
                        },
                        new
                        {
                            ID = 4,
                            AreaID = 1,
                            Descripcion = "Maquina Nro 4 del Area de Produccion Nro 1"
                        },
                        new
                        {
                            ID = 5,
                            AreaID = 1,
                            Descripcion = "Maquina Nro 5 del Area de Produccion Nro 1"
                        },
                        new
                        {
                            ID = 6,
                            AreaID = 2,
                            Descripcion = "Maquina Nro 6 del Area de Produccion Nro 2"
                        },
                        new
                        {
                            ID = 7,
                            AreaID = 2,
                            Descripcion = "Maquina Nro 7 del Area de Produccion Nro 2"
                        },
                        new
                        {
                            ID = 8,
                            AreaID = 2,
                            Descripcion = "Maquina Nro 8 del Area de Produccion Nro 2"
                        },
                        new
                        {
                            ID = 9,
                            AreaID = 2,
                            Descripcion = "Maquina Nro 9 del Area de Produccion Nro 2"
                        },
                        new
                        {
                            ID = 10,
                            AreaID = 2,
                            Descripcion = "Maquina Nro 10 del Area de Produccion Nro 2"
                        },
                        new
                        {
                            ID = 11,
                            AreaID = 3,
                            Descripcion = "Maquina Nro 11 del Area de Produccion Nro 3"
                        },
                        new
                        {
                            ID = 12,
                            AreaID = 3,
                            Descripcion = "Maquina Nro 12 del Area de Produccion Nro 3"
                        },
                        new
                        {
                            ID = 13,
                            AreaID = 3,
                            Descripcion = "Maquina Nro 13 del Area de Produccion Nro 3"
                        },
                        new
                        {
                            ID = 14,
                            AreaID = 4,
                            Descripcion = "Maquina Nro 14 del Area de Produccion Nro 4"
                        },
                        new
                        {
                            ID = 15,
                            AreaID = 4,
                            Descripcion = "Maquina Nro 15 del Area de Produccion Nro 4"
                        },
                        new
                        {
                            ID = 16,
                            AreaID = 4,
                            Descripcion = "Maquina Nro 16 del Area de Produccion Nro 4"
                        },
                        new
                        {
                            ID = 17,
                            AreaID = 4,
                            Descripcion = "Maquina Nro 17 del Area de Produccion Nro 4"
                        },
                        new
                        {
                            ID = 18,
                            AreaID = 4,
                            Descripcion = "Maquina Nro 18 del Area de Produccion Nro 4"
                        },
                        new
                        {
                            ID = 19,
                            AreaID = 4,
                            Descripcion = "Maquina Nro 19 del Area de Produccion Nro 4"
                        },
                        new
                        {
                            ID = 20,
                            AreaID = 5,
                            Descripcion = "Maquina Nro 20 del Area de Produccion Nro 5"
                        },
                        new
                        {
                            ID = 21,
                            AreaID = 5,
                            Descripcion = "Maquina Nro 21 del Area de Produccion Nro 5"
                        });
                });

            modelBuilder.Entity("ZF_AuditoriaCalidad.Shared.Observacion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AreaResponsableID")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ParaLaLinea")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("AreaResponsableID");

                    b.ToTable("tblObservaciones");
                });

            modelBuilder.Entity("ZF_AuditoriaCalidad.Shared.ObservacionDetalleAuditoria", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Contemplada")
                        .HasColumnType("bit");

                    b.Property<int>("DetalleAuditoriaID")
                        .HasColumnType("int");

                    b.Property<int>("ObservacionID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DetalleAuditoriaID");

                    b.ToTable("tblObservacionesDetalleAuditoria");
                });

            modelBuilder.Entity("ZF_AuditoriaCalidad.Shared.ObservacionNoContemplada", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AreaResponsableID")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ParaLaLinea")
                        .HasColumnType("bit");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AreaResponsableID");

                    b.ToTable("tblObservacionesNoContempladas");
                });

            modelBuilder.Entity("ZF_AuditoriaCalidad.Shared.Operario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<bool>("Auditor")
                        .HasColumnType("bit");

                    b.Property<string>("Legajo")
                        .HasColumnType("nvarchar(4)")
                        .HasMaxLength(4);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<bool>("Supervisor")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("tblOperarios");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Apellido = "Auditor 0001",
                            Auditor = true,
                            Legajo = "0001",
                            Nombre = "Operario",
                            Supervisor = false
                        },
                        new
                        {
                            ID = 2,
                            Apellido = "Auditor 0002",
                            Auditor = true,
                            Legajo = "0002",
                            Nombre = "Operario",
                            Supervisor = false
                        },
                        new
                        {
                            ID = 3,
                            Apellido = "Supervisor 0003",
                            Auditor = false,
                            Legajo = "0003",
                            Nombre = "Operario",
                            Supervisor = true
                        },
                        new
                        {
                            ID = 4,
                            Apellido = "Supervisor 0004",
                            Auditor = false,
                            Legajo = "0004",
                            Nombre = "Operario",
                            Supervisor = true
                        },
                        new
                        {
                            ID = 5,
                            Apellido = "0005",
                            Auditor = false,
                            Legajo = "0005",
                            Nombre = "Operario",
                            Supervisor = false
                        },
                        new
                        {
                            ID = 6,
                            Apellido = "0006",
                            Auditor = false,
                            Legajo = "0006",
                            Nombre = "Operario",
                            Supervisor = false
                        },
                        new
                        {
                            ID = 7,
                            Apellido = "0007",
                            Auditor = false,
                            Legajo = "0007",
                            Nombre = "Operario",
                            Supervisor = false
                        },
                        new
                        {
                            ID = 8,
                            Apellido = "0008",
                            Auditor = false,
                            Legajo = "0008",
                            Nombre = "Operario",
                            Supervisor = false
                        },
                        new
                        {
                            ID = 9,
                            Apellido = "0009",
                            Auditor = false,
                            Legajo = "0009",
                            Nombre = "Operario",
                            Supervisor = false
                        },
                        new
                        {
                            ID = 10,
                            Apellido = "0010",
                            Auditor = false,
                            Legajo = "0010",
                            Nombre = "Operario",
                            Supervisor = false
                        });
                });

            modelBuilder.Entity("ZF_AuditoriaCalidad.Shared.PuntoAuditoria", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("tblPuntosAuditoria");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Descripcion = "Punto de Auditoria Nro 1"
                        },
                        new
                        {
                            ID = 2,
                            Descripcion = "Punto de Auditoria Nro 2"
                        },
                        new
                        {
                            ID = 3,
                            Descripcion = "Punto de Auditoria Nro 3"
                        },
                        new
                        {
                            ID = 4,
                            Descripcion = "Punto de Auditoria Nro 4"
                        },
                        new
                        {
                            ID = 5,
                            Descripcion = "Punto de Auditoria Nro 5"
                        },
                        new
                        {
                            ID = 6,
                            Descripcion = "Punto de Auditoria Nro 6"
                        },
                        new
                        {
                            ID = 7,
                            Descripcion = "Punto de Auditoria Nro 7"
                        },
                        new
                        {
                            ID = 8,
                            Descripcion = "Punto de Auditoria Nro 8"
                        },
                        new
                        {
                            ID = 9,
                            Descripcion = "Punto de Auditoria Nro 9"
                        },
                        new
                        {
                            ID = 10,
                            Descripcion = "Punto de Auditoria Nro 10"
                        });
                });

            modelBuilder.Entity("ZF_AuditoriaCalidad.Shared.RespuestaDetalleAuditoria", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaseHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("tblRespuestasDetalleAuditoria");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ClaseHtml = "success",
                            Descripcion = "SI"
                        },
                        new
                        {
                            ID = 2,
                            ClaseHtml = "danger",
                            Descripcion = "NO"
                        },
                        new
                        {
                            ID = 3,
                            ClaseHtml = "warning",
                            Descripcion = "N/A"
                        },
                        new
                        {
                            ID = 4,
                            ClaseHtml = "info",
                            Descripcion = "Corregido"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ZF_AuditoriaCalidad.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ZF_AuditoriaCalidad.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZF_AuditoriaCalidad.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ZF_AuditoriaCalidad.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZF_AuditoriaCalidad.Shared.Auditoria", b =>
                {
                    b.HasOne("ZF_AuditoriaCalidad.Shared.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZF_AuditoriaCalidad.Shared.Operario", "Operario")
                        .WithMany()
                        .HasForeignKey("OperarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZF_AuditoriaCalidad.Shared.Operario", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZF_AuditoriaCalidad.Shared.DetalleAuditoria", b =>
                {
                    b.HasOne("ZF_AuditoriaCalidad.Shared.Auditoria", "Auditoria")
                        .WithMany("DetallesAuditoria")
                        .HasForeignKey("AuditoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZF_AuditoriaCalidad.Shared.PuntoAuditoria", "PuntoAuditoria")
                        .WithMany()
                        .HasForeignKey("PuntoAuditoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZF_AuditoriaCalidad.Shared.RespuestaDetalleAuditoria", "RespuestaDetalleAuditoria")
                        .WithMany()
                        .HasForeignKey("RespuestaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZF_AuditoriaCalidad.Shared.Maquina", b =>
                {
                    b.HasOne("ZF_AuditoriaCalidad.Shared.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZF_AuditoriaCalidad.Shared.Observacion", b =>
                {
                    b.HasOne("ZF_AuditoriaCalidad.Shared.Area", "AreaResponsable")
                        .WithMany()
                        .HasForeignKey("AreaResponsableID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZF_AuditoriaCalidad.Shared.ObservacionDetalleAuditoria", b =>
                {
                    b.HasOne("ZF_AuditoriaCalidad.Shared.DetalleAuditoria", "DetalleAuditoria")
                        .WithMany()
                        .HasForeignKey("DetalleAuditoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZF_AuditoriaCalidad.Shared.ObservacionNoContemplada", b =>
                {
                    b.HasOne("ZF_AuditoriaCalidad.Shared.Area", "AreaResponsable")
                        .WithMany()
                        .HasForeignKey("AreaResponsableID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
